options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.
      Supported Cloud Archive sources include:
      cloud:<series>-<openstack-release>
      cloud:<series>-<openstack-release>/updates
      cloud:<series>-<openstack-release>/staging
      cloud:<series>-<openstack-release>/proposed
      For series=Xenial we support cloud archives for openstack-release:
         * Mitaka
         * Newton
      NOTE: updating this setting to a source that is known to provide
      a later version of OpenStack will trigger a software upgrade.
  rabbit-user:
    default: trove
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  database-user:
    default: trove
    type: string
    description: Username for Trove database access (if enabled)
  database:
    default: trove
    type: string
    description: Database name for Trove (if enabled)
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging, deprecated in Newton
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  keystone-api-version:
    default: "2"
    type: string
    description: none,  2 or 3
  trove-volume-support:
    default: True
    type: boolean
    description: A cinder volume will be provisioned for all datastores (if enabled)
  trove-datastore-database:
    default: mysql
    type: string
    description: |
        One or more database type(s) for Trove datastores, list is comma separated,
        options are: mysql, redis, cassandra, mongodb, vertica
  trove-database-volume-support:
    default: mysql
    type: string
    description: |
        A cinder volume will be provisioned for individual datastores (if enabled)
        One or more database type(s) for Trove instances, list is comma separated,
        options are: mysql, redis, cassandra, mongodb, vertica
  default-neutron-networks:
    default:
    type: string
    description: |
        List of IDs for management networks which should be attached to the
        instance regardless of what NICs are specified in the create API call.
